import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  renderExploreCandidate,
  resolveExploreCandidatePath,
  writeExploreCandidate,
} from '../../src/explore/candidate.ts';
import type { ReportExplore } from '../../src/report/build.ts';

const roots: string[] = [];

function record(): ReportExplore {
  return {
    goal: 'Exercise checkout end to end',
    budgets: { maxSteps: 3, timeoutMs: 180_000 },
    ended: 'finished',
    summary: 'Checkout completed.',
    findings: [],
    steps: [
      {
        index: 1,
        title: 'Add product',
        instruction: 'Add the first product to the cart',
        status: 'passed',
        summary: 'The cart showed one item.',
        startedAt: '2026-10-03T19:00:00.000Z',
        durationMs: 10,
      },
      {
        index: 2,
        title: 'Unavailable payment',
        instruction: 'Try the unavailable payment route',
        status: 'blocked',
        summary: 'The provider was unavailable.',
        errorCode: 'ENVIRONMENT_UNAVAILABLE',
        startedAt: '2026-10-03T19:00:01.000Z',
        durationMs: 10,
      },
    ],
  };
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('explore test candidates', () => {
  it('renders passed charters as skipped action seeds with explicit verification debt', () => {
    const source = renderExploreCandidate(record(), {
      target: 'web',
      agent: 'buyer',
      session: 'admin',
      openApp: true,
    });

    expect(source).toContain("test.skip('Exercise checkout end to end', async ({ app, agent }) => {");
    expect(source).toContain('Source session: `admin`. Preserve it as a test option when enabling this candidate.');
    expect(source).toContain('preserve any source agent/session options');
    expect(source).toContain('await app.open()');
    expect(source).toContain("await agent.act(\"Add the first product to the cart\")");
    expect(source).toContain('// VERIFY: independently prove this transition');
    expect(source).toContain('step 2 (blocked): Unavailable payment');
    expect(source).not.toContain('await agent.act(\"Try the unavailable payment route\")');
  });

  it('writes only inside the project and never replaces an existing candidate', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'e2e-explore-candidate-'));
    roots.push(root);
    const target = resolveExploreCandidatePath(root, 'tests/checkout-candidate.e2e.ts');
    await writeExploreCandidate(target, record(), { target: 'web', agent: 'default', openApp: true });

    expect(await readFile(target, 'utf8')).toContain('Generated by `e2e explore --write-test`');
    await expect(
      writeExploreCandidate(target, record(), { target: 'web', agent: 'default', openApp: true }),
    ).rejects.toMatchObject({ code: 'INVALID_CONFIG' });
    expect(() => resolveExploreCandidatePath(root, '../outside.e2e.ts')).toThrow(/must stay inside the project/);
  });
});
