/**
 * A reviewable regression-test candidate from one successful exploration.
 *
 * Exploration is discovery, not verification: the generated file stays
 * skipped until a person replaces each VERIFY note with an independent,
 * deterministic oracle. The explored charters are preserved as `agent.act`
 * seeds so no model-authored success claim silently becomes test truth.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ConfigurationError } from '../internal/errors.ts';
import { relativeToProjectRoot } from '../internal/paths.ts';
import type { ReportExplore, ReportExploreStep } from '../report/build.ts';

export interface ExploreCandidateContext {
  readonly target: string;
  readonly agent: string;
  readonly session?: string | undefined;
  readonly openApp: boolean;
}

/** Resolves a requested candidate path and refuses writes outside the project. */
export function resolveExploreCandidatePath(projectRoot: string, requested: string): string {
  const trimmed = requested.trim();
  if (trimmed === '') {
    throw new ConfigurationError('INVALID_CONFIG', '--write-test needs a non-empty path');
  }
  if (path.isAbsolute(trimmed)) {
    throw new ConfigurationError('INVALID_CONFIG', `--write-test must be relative to the project root, got ${JSON.stringify(requested)}`);
  }
  const target = path.resolve(projectRoot, trimmed);
  if (relativeToProjectRoot(projectRoot, target) === undefined) {
    throw new ConfigurationError('INVALID_CONFIG', `--write-test must stay inside the project, got ${JSON.stringify(requested)}`);
  }
  return target;
}

/** Writes a candidate once; an existing file is never replaced implicitly. */
export async function writeExploreCandidate(
  filePath: string,
  explore: ReportExplore,
  context: ExploreCandidateContext,
): Promise<void> {
  const passed = explore.steps.filter((step) => step.status === 'passed');
  if (passed.length === 0) {
    throw new ConfigurationError('INVALID_CONFIG', '--write-test needs at least one passed exploration step');
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  try {
    await writeFile(filePath, renderExploreCandidate(explore, context), { encoding: 'utf8', flag: 'wx' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ConfigurationError('INVALID_CONFIG', `--write-test refuses to replace existing file ${filePath}`);
    }
    throw cause;
  }
}

/** Renders a skipped test scaffold whose verification debt is explicit. */
export function renderExploreCandidate(explore: ReportExplore, context: ExploreCandidateContext): string {
  const passed = explore.steps.filter((step) => step.status === 'passed');
  const incomplete = explore.steps.filter((step) => step.status !== 'passed');
  const lines = [
    "import { test } from 'e2e';",
    '',
    '// Generated by `e2e explore --write-test` from a discovery run.',
    `// Source target: ${code(context.target)}. Source agent: ${code(context.agent)}.`,
    ...(context.session === undefined ? [] : [`// Source session: ${code(context.session)}. Preserve it as a test option when enabling this candidate.`]),
    '// This file is collection-time skipped: exploration success is not an independent oracle.',
    '// Promotion requirement: replace every `VERIFY` note with deterministic checks, preserve any source agent/session options, then change `test.skip(...)` to `test(...)`.',
    '',
    `test.skip(${JSON.stringify(explore.goal)}, async ({ app, agent }) => {`,
    ...(context.openApp ? ['  await app.open();', ''] : []),
  ];

  for (const step of passed) {
    lines.push(
      `  // Journey step ${step.index}: ${oneLine(step.title)}`,
      `  await agent.act(${JSON.stringify(step.instruction)});`,
      `  // VERIFY: independently prove this transition's effect.${summarySuffix(step)}`,
      '',
    );
  }

  if (incomplete.length > 0) {
    lines.push(
      '  // Not compiled from the exploration because these charters did not pass:',
      ...incomplete.map((step) => `  // - step ${step.index} (${step.status}): ${oneLine(step.title)}`),
      '',
    );
  }

  lines.push('});', '');
  return lines.join('\n');
}

function summarySuffix(step: ReportExploreStep): string {
  return step.summary === undefined ? '' : ` Exploration summary: ${JSON.stringify(oneLine(step.summary))}`;
}

function oneLine(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function code(value: string): string {
  return `\`${oneLine(value).replace(/\`/g, '\\\`')}\``;
}
